{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

let
  inherit (pkgs.stdenv.hostPlatform) system;

  autoFollow = lib.getExe' inputs.nix-auto-follow.packages.${system}.default "auto-follow";

  treefmt = import ./treefmt.nix { inherit pkgs; };
in
{
  # https://devenv.sh/packages/
  packages = with pkgs; [
    git
    just
    jq
    sops
    nil
    statix
    deadnix
    treefmt
    inputs.nix-auto-follow.packages.${system}.default
  ];

  # https://devenv.sh/languages/
  languages = {
    nix.enable = true;
    shell.enable = true;
  };

  # `devenv test` runs git-hooks against the whole repo before enterTest, so
  # treefmt/statix/deadnix are exercised there already -- no need to re-invoke
  # them here (and doing so would mean maintaining their settings twice).
  # https://devenv.sh/tests/

  # https://devenv.sh/git-hooks/
  git-hooks.hooks = {
    action-validator.enable = true;
    actionlint.enable = true;
    check-merge-conflicts.enable = true;
    nil.enable = true;
    shellcheck.enable = true;

    statix = {
      enable = true;
      settings.ignore = [
        # Generated by nixos-generate-config; not meant to be hand-edited or restyled.
        "nixos/configurations/hardware/*.nix"
      ];
    };

    # NixOS/home-manager modules and flake-parts perSystem are called by a framework
    # with a fixed argument set, so unused module args are expected and shouldn't be
    # flagged as dead code (same reasoning as nixpkgs callPackage).
    deadnix = {
      enable = true;
      settings.noLambdaPatternNames = true;
    };

    treefmt = {
      enable = true;
      packageOverrides.treefmt = treefmt;
    };

    # Fails the commit if flake.lock's `inputs.*.follows` aren't deduplicated,
    nix-auto-follow = {
      enable = true;
      name = "nix-auto-follow";
      description = "Check flake.lock inputs.*.follows are deduplicated via nix-auto-follow";
      entry = "${autoFollow} --check";
      files = "^flake\\.lock$";
      pass_filenames = false;
    };
  };

  difftastic.enable = true;

  claude.code = {
    enable = true;
    mcpServers = {
      devenv = {
        type = "stdio";
        command = "devenv";
        args = [ "mcp" ];
        env = {
          DEVENV_ROOT = config.devenv.root;
        };
      };
    };
  };

  # See full reference at https://devenv.sh/reference/options/
}
